baseURL = "https://id-is.github.io"
languageCode = "en-us"
title = "INTELLIGENT DATA-INTENSIVE SYSTEMS"
theme = "mainroad"

[params]
  text_color = "black"
  site_logo = "/id_is_logo.png"
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-lightest-blue"
  recent_posts_number = 3
  # Add custom styling for the title
  title_style = "font-family: 'Arial', sans-serif; font-size: 2.5em; font-weight: bold; color: #333; text-transform: uppercase; letter-spacing: 2px;"
  scssDir = "assets/scss"
  


[menu]
[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/home/'
    weight = 1
[[menu.main]]
    identifier = 'team'
    name = 'Team'
    url = '/team/'
    weight = 4
[[menu.main]]
    identifier = 'Software and Resources'
    name = 'Software and Resources'
    url = '/software_resources/'
    weight = 5
[[menu.main]]
    identifier = 'Projects'
    name = 'Projects'
    url = '/projects/'
    weight = 2
[[menu.main]]
    identifier = 'Publications'
    name = 'Publications'
    url = '/publications/'
    weight = 3

[markup.goldmark.renderer]
  unsafe = true
